### ISSUE TITLE
1.9.2?

### ISSUE THREAD

**Issue by Craftaris** [ImMaury/AdvancedBugReporter#1]
The plugin doesn't seem to work on 1.9.2 :( But the concept is just perfect for any server

I have tested it on 1.9. Works very well! Could you update it to 1.9.2?

**Comment by ImMaury** [comment]
Well, that's odd enough. I tried it on the latest Spigot release and it worked fine.
What Java version are you using?
Also, what errors do the logs show?

**Comment by Craftaris** [comment]
Java 7 

02.05 21:54:49 [Server] ERROR Could not load 'plugins/AdvancedBugReporter.jar' in folder 'plugins'
02.05 21:54:49 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/im_maury/advancedbugreporter/Main : Unsupported major.minor version 52.0
02.05 21:54:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
02.05 21:54:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
02.05 21:54:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
02.05 21:54:49 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
02.05 21:54:49 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
02.05 21:54:49 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]

**Comment by ImMaury** [comment]
Try the new release and let me know if everything works fine.

**Comment by Craftaris** [comment]
It works! Thank you for your help and willingness to update the plugin!
I just need to double check the remove command, but the report, checking and teleport are working perfectly!

Thank you!

**Comment by Craftaris** [comment]
Yeah, the delete command doesn't quite work

Edit: I have also tried to add permission via PermissionEx and they don't seem to work correctly

**Comment by ImMaury** [comment]
I edited the permission nodes a while ago but haven't remembered to update the wiki. Try the new permissions.
What's the matter with /reportdel?

**Comment by Craftaris** [comment]
Hi, the new permission are working fine! Just the /reportdel doesn't seem to be working at all. 
Everytime I enter /reporterdel 1 - I receive the following message: Incorrect usage. Type /bugreporter help for more info.

**Comment by ImMaury** [comment]
The format for the command  `/reportdel` is:

> /reportdel [selector] [value1] [value2] [...]

So the right command would be:

> /reportdel id 1

**Comment by Craftaris** [comment]
It works! Thank you for your support!

**Comment by ImMaury** [comment]
You're welcome.
Consider leaving a review on Spigot if you enjoyed the plugin ;)
